export const CURATED_PROMPTS: string[] = [
  "A steampunk airship with a wooden hull, large brass propellers on each side, a balloon made of patchwork fabric above the deck, hanging ropes and ladders, and a glass-enclosed bridge at the front",
  "A flying aircraft carrier with a flat deck on top, control tower, planes parked on deck, massive jet engines underneath keeping it aloft, and radar dishes",
  "A steam locomotive",
  "A skyscraper",
  "A treehouse village: three large treehouses in adjacent trees connected by rope bridges, each house with different architecture (one rustic, one elvish with curved lines, one modern with clean angles), rope ladders down, and lanterns hanging from branches",
  "A cozy cottage",
  "A massive world tree: an enormous trunk with roots visible above ground forming archways, multiple levels of thick branches like platforms, glowing fruit hanging from smaller branches, and vines draping down",
  "A floating island ecosystem: a chunk of earth suspended in air with waterfalls pouring off multiple edges, a small forest on top (with a larger central tree), exposed roots and rocks hanging underneath, and smaller floating rocks nearby connected by ancient chain bridges.",
  "An underwater shipwreck: a wooden galleon on its side on the ocean floor, holes in the hull, coral and seaweed growing on it, treasure chests spilling gold, and fish swimming around",
  "A phoenix rising from flames: wings fully spread upward, tail feathers flowing down like fire, head raised to the sky, made of red, orange, and gold blocks with glowstone accents",
  "A knight in armor",
  "A medieval stone castle with curtain walls forming a square, four tall corner towers with battlements, a central keep, a gatehouse with an archway and portcullis, and a surrounding moat with a small drawbridge.",
  "A classic arcade cabinet with a joystick and three buttons on the control panel, a screen showing simple graphics, coin slot on the front, and artwork on the sides",
  "An astronaut",
  "A fighter jet",
  "A figure skater performing a Biellmann spin",
  "A Formula One car",
  "A pelican riding a bicycle",
  "A fully accurate globe of the Earth",
  "A space shuttle on a launch pad with booster rockets, gantry arms, flame trench, and service tower",
  "An analog clock showcasing the time of 1:17 and 47 seconds",
  "An accurate representation of the New York City skyline",
  "A chess game in progress with captured pieces beside the board, and one king in check",
  "A snow globe containing a tiny winter village",
  "An accurate representation of the Solar System",
  "A fully accurate MacBook home screen",
  "A classroom chalkboard showing the solved integral of x squared from 0 to 3, with the full work written on the board",
  "A representation of the Pythagorean theorem",
  "The Golden Gate Bridge",
];
